"""Hand-editable axis definitions for build_grid.py.

Rules are ORDERED and FIRST MATCH WINS, so specific named models sit above generic
ones. Matching runs on the normalised (lowercased, whitespace- and separator-collapsed)
disease_model.components joined into one string, so "Db/ db", "db / db" and "db/db"
all match the same pattern.

  {"any": [...]}           -> matches if any pattern is present
  {"all": [[...], [...]]}  -> matches only if EACH inner group has a hit
                              (two-hit models such as HFD + L-NAME)

A word-like pattern ("aged") is matched on word boundaries, so it will not fire inside
"packaged" or "damaged". Patterns containing punctuation ("db/db", "(tac)", "-/-") are
matched as plain substrings.
"""

# --- species axis: matched against the species_mesh column of corpus.csv -----------
SPECIES_RULES = [
    ("Mouse",  ["mice", "mus musculus"]),
    ("Rat",    ["rats", "rattus"]),
    ("Pig",    ["swine", "sus scrofa"]),
    ("Dog",    ["dogs", "canis"]),
    ("Rabbit", ["rabbits", "oryctolagus"]),
]
SPECIES_FALLBACK = "Other"
SPECIES_AXIS = [s for s, _ in SPECIES_RULES] + [SPECIES_FALLBACK]
# A paper tagged with several species goes to the FIRST rule that matches; the full
# MeSH string is kept in the cell detail so nothing is lost.

# --- model axis -------------------------------------------------------------------
# Order notes:
#   ZSF1 precedes SHR and ZDF -- its full name contains "Zucker" and "spontaneously
#     hypertensive", so it would otherwise be captured by them.
#   HFD+L-NAME precedes everything diet-related; bare HFD sits LAST before the
#     fallbacks so it only fires when no second hit was found.
#   DOCA-salt precedes CKD -- the DOCA model routinely includes uninephrectomy.
#   IR precedes MI -- reperfusion studies also say "myocardial infarction".
MODEL_RULES = [
    ("ZSF1",                  {"any": ["zsf1", "zsf-1"]}),
    ("ZDF",                   {"any": ["zdf", "zucker diabetic fatty"]}),
    ("Dahl salt-sensitive",   {"any": ["dahl"]}),
    ("SHR",                   {"any": ["shr", "shrs", "spontaneously hypertensive"]}),
    ("db/db",                 {"any": ["db/db", "dbdb", "db/db mouse", "db/db mice"]}),
    ("HFD+L-NAME",            {"all": [["high-fat", "high fat", "hfd", "western diet"],
                                       ["l-name", "nitro-l-arginine", "lname"]]}),
    ("DOCA-salt",             {"any": ["doca", "deoxycorticosterone", "desoxycorticosterone"]}),
    ("Ang II",                {"any": ["angiotensin ii", "angiotensin-ii", "ang ii",
                                       "angii", "ang-ii"]}),
    ("TAC/pressure-overload", {"any": ["transverse aortic constriction", "aortic constriction",
                                       "aortic banding", "pressure overload", "tac",
                                       "(tac)", "aortic ligation"]}),
    ("IR",                    {"any": ["ischemia-reperfusion", "ischaemia-reperfusion",
                                       "ischemia/reperfusion", "ischaemia/reperfusion",
                                       "i/r injury", "transient occlusion",
                                       "transient ligation", "reperfusion"]}),
    ("MI",                    {"any": ["myocardial infarction", "coronary ligation",
                                       "coronary artery ligation", "lad ligation",
                                       "permanent ligation", "permanent occlusion",
                                       "left anterior descending"]}),
    ("isoproterenol",         {"any": ["isoproterenol", "isoprenaline", "(iso)"]}),
    ("STZ",                   {"any": ["streptozotocin", "streptozocin", "stz"]}),
    ("doxorubicin",           {"any": ["doxorubicin", "adriamycin"]}),
    ("pacing",                {"any": ["tachypacing", "tachy-pacing", "rapid pacing",
                                       "rapid ventricular pacing", "pacing-induced",
                                       "ventricular pacing", "atrial pacing"]}),
    ("CKD",                   {"any": ["nephrectomy", "uninephrectomy", "5/6 subtotal",
                                       "subtotal nephrectomy", "renal mass reduction",
                                       "chronic kidney disease", "adenine diet",
                                       "renal ablation"]}),
    ("aged",                  {"any": ["aged", "aging", "ageing", "senescent",
                                       "senescence", "old mice", "old rats"]}),
    # bare diet with no second hit -- last, so any co-occurring driver wins first
    ("HFD",                   {"any": ["high-fat", "high fat", "hfd", "western diet",
                                       "high-fat high-salt"]}),
]
MODEL_FALLBACK_GENETIC = "other-genetic"        # model_type == genetic_strain
MODEL_FALLBACK_OTHER = "other-combination"
GENETIC_HINTS = ["knockout", "knock-out", "transgenic", "ob/ob", "zucker", "-/-",
                 "null mice", "mutant", "knockin", "knock-in", "knockdown"]
MODEL_AXIS = [m for m, _ in MODEL_RULES] + [MODEL_FALLBACK_GENETIC, MODEL_FALLBACK_OTHER]

# --- heart-failure phenotype each model is normally taken to represent -------------
HF_CLASS = {
    "ZSF1": "hfpef", "Dahl salt-sensitive": "hfpef", "db/db": "hfpef", "ZDF": "hfpef",
    "SHR": "hfpef", "HFD": "hfpef", "HFD+L-NAME": "hfpef", "DOCA-salt": "hfpef",
    "aged": "hfpef", "CKD": "hfpef",
    "MI": "hfref", "IR": "hfref", "isoproterenol": "hfref", "pacing": "hfref",
    "doxorubicin": "hfref",
    "TAC/pressure-overload": "mixed", "Ang II": "mixed", "STZ": "mixed",
    "other-genetic": "unclassified", "other-combination": "unclassified",
}

# --- outcome axis: the extraction enum, used as-is --------------------------------
OUTCOME_AXIS = ["cardiac", "vascular", "pulmonary", "skeletal_muscle", "metabolic",
                "renal", "molecular", "histological", "behavioral_exercise", "other"]

# --- species x model pairs that cannot exist --------------------------------------
# Rendered as a fourth cell state; never counted as a gap, never used in adjacency.
NOT_APPLICABLE = {
    ("Mouse", "ZSF1"),                  # rat strain
    ("Mouse", "Dahl salt-sensitive"),   # rat strain
    ("Mouse", "ZDF"),                   # rat strain
    ("Mouse", "SHR"),                   # rat strain
    ("Rat", "db/db"),                   # mouse Lepr mutation
}

# --- cell status thresholds -------------------------------------------------------
# An empty cell is only "no_evidence_found" when enough papers sat at that
# species x model pair to have reported the outcome. Below this it is "unscreened".
MIN_SCREENED = 3

# --- outcome-measure canonicalisation ---------------------------------------------
# Verbatim measure phrases collapse to a canonical measure so that two papers reporting
# "E/e' ratio" and "diastolic dysfunction" are recognised as measuring the same thing.
# Generated once by clustering every distinct phrase in the corpus; hand-edit freely.
# Keys are canonical names, values are the verbatim phrases (already lowercased and
# separator-normalised) that map onto them. build_grid.py inverts this at import.
MEASURE_GROUPS = {
    "protein_expression": [
        "abundance",
        "abundance of titin isoforms and their ratio",
        "acetyl-p53/cd31 costaining",
        "acetylome",
        "active glucagon-like peptide-1",
        "acyl-coa synthetase long-chain family member 4",
        "adipor",
        "aim2 protein levels",
        "aldh2 levels",
        "aldh2 levels and activity",
        "alpha-5 integrin protein expression",
        "atrophy-related proteins",
        "b2m",
        "circulation and protein expression levels of loxl2",
        "cmybp-c",
        "cnpy2 levels",
        "cofilin-2 expression",
        "connexin 43 expression",
        "connexin43",
        "connexin43 expression",
        "endothelial nitric oxide synthase (enos) expression",
        "endothelial nos monomer",
        "enos",
        "expression and nuclear localization of hdac4",
        "expression levels of cnpy2",
        "expression levels of resistin-like molecule gamma (relmg)",
        "expression of >100 extracellular matrix proteins in lvs",
        "expression of age-modified proteins",
        "expression of apoptosis-related proteins",
        "expression of cardiac glycolytic enzymes",
        "expression of contraction regulating proteins",
        "expression of enos",
        "expression of gc",
        "expression of hif-1\u03b1 (hypoxia-inducible factor-1\u03b1)",
        "expression of inos, sno-pten, and p-akt",
        "expression of jp-2",
        "expression of key fhf long isoforms",
        "expression of nnmt",
        "expression of npra",
        "expression of profibrotic/prohypertrophic proteins",
        "expression of proteins involved in glucose (sglt2, glut4, gpd1) and ca2+ and na + homeostasis (ncx3, ryr1, nhe1/6, na+/k+-atpase, nav1.4)",
        "expression of ucp3",
        "expression/activation of endothelial nitric oxide synthase (enos)",
        "expressions of enos",
        "expressions of mitofilin, mfn-2, fis1, and mick",
        "expressions of p-ampk and pgc-1\u03b1",
        "expressions of pkg i",
        "fast troponin i",
        "ferritin heavy chain 1",
        "ferroportin 1",
        "fibronectin protein expression",
        "fmo3",
        "gal-3, gdf-15 and timp-1 cardiac expressions",
        "gdf8",
        "glutathione peroxidase 4",
        "glutathione peroxidase 4 (gpx-4)",
        "gluts (glucose transporters)",
        "gpx1",
        "gpx4, xct, and fsp-1 expression",
        "growth differentiation factor 15",
        "hbb",
        "idh2",
        "inos",
        "intercellular adhesion molecule 1 expression",
        "kv4.3",
        "kv4.3 protein levels",
        "levels of desmin and alpha-actinin",
        "levels of serca-2",
        "markers for catabolism (murf1, mafbx)",
        "markers of protein translation",
        "mitochondrial ca2+ uniporter protein",
        "mitofilin",
        "mmp-2",
        "mmp2",
        "mmp9",
        "mpo protein",
        "murf1",
        "murf1 content",
        "murf1 expression, protein ubiquitinylation, and lc3",
        "myeloperoxidase (mpo)",
        "myhc isoform-switch",
        "myocardial expression of calcium transporter ryanodine receptor 2 (ryr2) and \u03b1-myosin heavy chain (mhc), with a lower expression of \u03b2-mhc",
        "myocardial expression of glp-1 receptors",
        "myocardial tgfbr1 expression",
        "myosin heavy chain isoforms",
        "nadph oxidase expression",
        "ncx expression",
        "ncx protein expression",
        "ncx1",
        "nnos expression",
        "no-producing dimeric form",
        "nos1 (neuronal nos) expression",
        "notch-1",
        "nox4",
        "nox4 expression",
        "p-ampk and pgc-1\u03b1 downregulation",
        "p-drp1 and fis1 expression",
        "p-smad3 protein",
        "pcpe-1 expression in the lv",
        "pcpe-1, whose expression increased in bat with aging",
        "pde5 expression",
        "pde5a expression",
        "piezo1 expression",
        "pink1 and prdx2 were downregulated",
        "pkc \u03b1, \u03b2, and \u03b4 concentration",
        "pkc\u03b2 concentration",
        "pkg expression and activity",
        "plasminogen inhibitor activator 1 (pai-1)",
        "prdx2 expression",
        "prdx2 levels",
        "proangiogenic growth factors",
        "procollagen c-endopeptidase enhancer-1 (pcpe-1)",
        "protein expression in murf1 and murf2",
        "protein expression levels of ang \u2171, tgf-\u03b21, p-smad2/3, and mmp-9",
        "protein expression of enos",
        "protein expression of galectin-3",
        "protein expression of serca2",
        "protein expressions of antioxidants [sirtuin-1 (sirt1)/sirt3/superoxide dismutase/catalase/glutathione peroxidase)",
        "protein expressions of apoptotic (mitochondrial-bax/cleaved-caspase-3/cleaved-parp)",
        "protein expressions of cleaved-caspase3",
        "protein expressions of dna/mitochondrial-damage (\u03b3-h2ax/cytosolic-cytochrome-c)",
        "protein expressions of fibrotic (transforming-growth factor-\u00df/smad3)",
        "protein expressions of inflammatory (tumor-necrosis factor-\u03b1/nuclear-factor-\u03bab/interleukin-1\u00df/matrix-metalloprotianse-9)",
        "protein expressions of nlrp3 and nf-\u03bab pathways",
        "protein expressions of oxidative stress (nox-1/nox-2/oxidized protein)",
        "protein expressions of oxidative-stress (nox-1/nox-2/oxidized protein)",
        "protein level of angiotensin converting enzyme 2",
        "protein level of prdx5",
        "protein level of the at1 receptor",
        "protein levels of oxidative-stress/dna-damaged markers [nadph-oxidase-1 (nox-1)/nox-2/oxidized-protein/\u03b3-h2a-histone-family member x (\u03b3-h2ax)]",
        "protein-to-tryptophan ratio",
        "proteome",
        "pyruvate dehydrogenase kinase 4 content",
        "ratio nos3 dimer/nos3 monomer",
        "ratio of at1 over at2 receptor",
        "s100a9 is significantly elevated in both cardiac tissue and serum",
        "sarcoplasmic reticulum ca2+ atpase expression",
        "secretion levels of loxl2",
        "secretion of c1q/tumour necrosis factor-related protein 3 (ctrp3) by adipose tissue",
        "serca2",
        "serca2 expression",
        "serca2a downregulation",
        "serca2a/phospholamban ratio",
        "sgc\u03b21 expression",
        "sglt2 renal expression",
        "sirt3 levels",
        "slow troponin c",
        "smad2",
        "smad3",
        "smad7 mrna and protein expressions",
        "sno-pten, pten, p-pi3k, p-akt, cell proliferation and migration, collagen i and iii expression",
        "sod1",
        "tax1bp1 mrna and protein",
        "tgf (transforming growth factor)-beta and ctgf (connective tissue growth factor) levels",
        "tgf-beta1, smad2, smad3, p-smad2/smad3, smad4, alpha-sma, and coll i protein expressions",
        "tgf-\u03b2",
        "tgf-\u03b21",
        "titin isoform n2b",
        "titin n2b isoform expression",
        "tnc expression",
        "transferrin receptor",
        "troponin i",
        "trx2 and gsnor",
        "usp38 expression",
        "vcam1",
        "vegfr2",
        "wnt1",
        "wnt1, 2, 10b messenger rna and \u03b2-catenin protein expression levels in the left ventricle",
        "\u03b1-smooth muscle actin (\u03b1-sma)",
        "\u03b1-smooth muscle actin, transforming growth factor-\u03b21, and connective tissue growth factor",
        "\u03b2-catenin",
    ],
    "diastolic_function": [
        "-dp/dtmin",
        "age-associated lvdd",
        "alteration of dp/dt min",
        "cardiac diastolic dysfunction",
        "cardiac diastolic function",
        "cardiac filling in diastole",
        "chamber compliance",
        "compliance at neonatal stage",
        "dd",
        "deceleration and isovolumic relaxation time",
        "delayed left ventricular relaxation",
        "delayed ventricular relaxation",
        "diastolic abnormalities",
        "diastolic cardiac function",
        "diastolic compliance",
        "diastolic dysfunction",
        "diastolic dysfunction (e.g., end-diastolic pressure and relaxation time constant)",
        "diastolic dysfunction (e/e')",
        "diastolic dysfunction (increased lv/cardiomyocyte stiffness, prolonged lv relaxation time)",
        "diastolic dysfunction and arrhythmogenesis",
        "diastolic dysfunction and heart failure symptoms",
        "diastolic dysfunction and metabolic abnormalities",
        "diastolic dysfunction with preserved ejection fraction",
        "diastolic dysfunction with preserved systolic function",
        "diastolic echocardiographic parameters",
        "diastolic function",
        "diastolic function (e/a ratio)",
        "diastolic function parameters",
        "diastolic indices",
        "diastolic relaxation",
        "doppler e/e'",
        "dp/dt min",
        "dr/dtmax",
        "e and a wave velocities",
        "e peak velocity",
        "e/a",
        "e/a ratio",
        "e/a ratios",
        "e/a value",
        "e/e'",
        "e/e' and e'/a' ratios",
        "e/e' ratio",
        "e/e' ratios",
        "e/early diastolic circumferential strain rate",
        "e/\u00e9",
        "e/\u00e9 ratios",
        "early (e) and late (a) filling peak velocities",
        "early diastolic dysfunction",
        "early diastolic tissue doppler velocities in the lv",
        "early to late diastolic transmitral flow velocity (e/a) ratio",
        "echocardiographic e/a ratio",
        "edpvr",
        "end-diastolic pressure-volume relationship",
        "end-diastolic pressure-volume relationship (edpvr)",
        "end-diastolic pressure-volume relationships",
        "impaired diastolic function",
        "impaired diastolic relaxation",
        "impaired lv relaxation",
        "improved diastolic function",
        "in vivo diastolic function",
        "incomplete relaxation",
        "isovolumetric relaxation time",
        "isovolumetric relaxation time (ivrt)",
        "isovolumetric relaxation time constant",
        "isovolumic relaxation time",
        "isovolumic relaxation time (ivrt)",
        "isovolumic relaxation time of the lv",
        "ivrt",
        "lateral e'",
        "lateral e/e'",
        "left atrial area, e/a and e'/a' ratios",
        "left end-diastolic function (e/e' ratio)",
        "left ventricle diastolic function",
        "left ventricular (lv) filling pressure (<e/e' ratio)",
        "left ventricular diastolic dysfunction",
        "left ventricular diastolic dysfunction with preserved ejection fraction",
        "left ventricular diastolic dysfunctions",
        "left ventricular diastolic function",
        "left ventricular diastolic function and global longitudinal strain",
        "left ventricular relaxation time constants",
        "lusitropic effect",
        "lusitropism in adult hearts",
        "lv compliance",
        "lv diastolic dysfunction",
        "lv diastolic dysfunction with preserved ejection fraction",
        "lv diastolic function",
        "lv end-diastolic pressure-volume relationship",
        "lv isovolumetric relaxation time",
        "lv peak inflow velocities",
        "lv peak-dp/dt",
        "lv relaxation",
        "lv time constant of relaxation (\u03c4)",
        "lvdd",
        "maximum mitral valve blood flow in systolic period (a)",
        "minimum and end-diastolic pressure and relaxation time constant",
        "mitral flow (dv/dtmax)",
        "mitral ring myocardial movement velocity in early diastolic period (e')",
        "myocardial relaxation",
        "myocardial relaxation velocity",
        "passive lv pressure volume curves",
        "peak diastolic velocity",
        "peak early (e) and peak late atrial (a) transmitral inflow velocities",
        "peak velocity of mitral valve blood flow in early diastolic period (e)",
        "pfr",
        "pressure decay time constant \u03c4-glantz",
        "prolonged lv isovolumetric relaxation constant tau (ivrc tau)",
        "relaxation",
        "relaxation (dr/dtmax)",
        "relaxation and cat decay",
        "relaxation impairment",
        "relaxation in isolated human cardiomyocytes",
        "relaxation in nxt in vivo and in cardiomyocytes",
        "relaxation kinetics",
        "relaxation time",
        "relaxation time constant",
        "relaxation time constant (tau)",
        "septal wall motion (>tissue doppler derived e'/a' ratio)",
        "slope of the end-diastolic pressure-volume relationship",
        "tau",
        "time constant",
        "time constant of isovolumic relaxation (\u03b3)",
        "time contraction of isovolumic diastolic time (ivrt)",
        "ventricular filling dynamics",
        "ventricular relaxation",
        "worsening of diastolic dysfunction over time",
    ],
    "gene_expression": [
        "actn4, but not actn2, was upregulated in the left ventricular following pressure overload",
        "adipose tissue expression",
        "adp/atp translocase 1 mrna levels",
        "angptl4 expression",
        "arginase 1 expression",
        "at2 receptor was upregulated",
        "bnip3 expression",
        "cardiac conduction, striated muscle contraction, and sphingolipid homeostasis gene expression differences",
        "cardiac genes associated with fibrosis, inflammation, apoptosis, oxidative stress, and ion channel function",
        "cardiac mirna expression profile",
        "cardiac tf mrna and protein levels",
        "cardiac transcripts of proinflammatory cytokines and profibrotic markers",
        "cox2 expression",
        "ctgf, col1a1, col3a1, and nppa",
        "differentially expressed genes (degs)",
        "effects of setd2 deletion",
        "efhd1 expression",
        "expression levels of ... adenylate cyclase 1 (adcy1)",
        "expression levels of fibrosis-and hypertrophy-related genes",
        "expression levels of genes encoding certain pro-angiogenic secreted proteins",
        "expression of genes encoding mitochondrial proteins",
        "expression of mir-132",
        "expression of mir-24",
        "expression of mitochondrial function-related genes",
        "expression of most of the components under investigation",
        "expression of proinflammatory cytokines",
        "expression of \u03b2-myhc ( myh7, p = 0.0002)",
        "expressions of genes associated with myocardial hypertrophy, fibrosis and apoptosis",
        "fetal gene reprogramming",
        "gdf15 mrna levels",
        "gene clustering in hfpef lungs",
        "gene expression",
        "gene expression markers for cardiac hypertrophy and fibrosis",
        "gene expression of mir-106b-5p",
        "gene expression of mir-137",
        "gene expression of proinflammatory cytokines",
        "gene expression profiles",
        "gene expression related to hypertrophy, fibrosis, and mitochondrial energy production",
        "gene markers of lv hypertrophy or extracellular matrix remodeling",
        "id2 expression",
        "inflammatory gene expression",
        "kcnd3",
        "kcnd3 transcript",
        "left atrial gene expression",
        "left ventricular gene expression",
        "left ventricular mrna expression of bnp",
        "left ventricular mrna expression of collagen",
        "lncrnas",
        "lung expression of preproendothelin-1",
        "lv expression of 170 genes",
        "lv mrna and protein expression",
        "lv mrna expression of genes that mediate active lv diastolic function",
        "micrornas",
        "mir-146a",
        "mir-30d-5p and mir-30e-5p in circulating evs",
        "mitochondrial gene expression",
        "mr target gene expression and markers of cardiac remodeling",
        "mrna cardiac gene expression",
        "mrna expression level of timp-1",
        "mrna expression levels of ang \u2171, at1r, tgf-\u03b21, smad2, smad3, and mmp-9",
        "mrna expression of \u03b1-myhc ( myh6, p = 0.03)",
        "mrna expressions of ccl2",
        "mrna expressions of tnf\u03b1",
        "mrna levels of the master regulator of calcium uptake by the mitochondria (micu1)",
        "mrna-sequencing analysis",
        "mrnas",
        "multiple ion channels gene expression",
        "nppa mrna levels",
        "nppb level",
        "pai-1 expression",
        "pro-hypertrophic gene expression",
        "pro-inflammatory and pro-fibrotic gene expression",
        "pro-inflammatory gene expression",
        "profibrotic and matrix gene expression",
        "pulmonary artery endothelial cell and pulmonary artery smooth muscle cell expression of cnpy2",
        "pyruvate dehydrogenase kinase 4 (pdk4) upregulation",
        "renal fibrotic gene expression",
        "sesn3 upregulation",
        "srebp1 upregulation",
        "tgf-beta1, smad2, smad3, smad4, alpha-sma, coll i, and coll iii mrna expressions",
        "transcript levels of ferroptosis-related hub degs",
        "type i collagen messenger rna expression levels",
        "xbp1s transcript levels",
    ],
    "cardiac_function": [
        "adrenergic sensitivity",
        "alterations consistent with heart failure with preserved ejection fraction (hfpef)",
        "atrial in vivo function",
        "baseline contractile performance",
        "cardiac diastolic and systolic function",
        "cardiac dysfunction",
        "cardiac dysfunction (hfpef)",
        "cardiac dysfunction with preserved ejection fraction",
        "cardiac function",
        "cardiac function impairment",
        "cardiac function parameters suggestive of hfpef",
        "cardiac impairment with reduced ejection fraction",
        "cardiac index",
        "cardiac output",
        "cardiac output (co)",
        "cardiac output reserve",
        "cardiac phenotypes of hfpef",
        "cardiac reserve",
        "cardiac structural and functional alterations",
        "cardiac sympathetic drive",
        "cardiac sympathoexcitation",
        "cardiac systolic and diastolic function",
        "cardiac \u03b2-ar subtypes modulation",
        "cardiorenal damage",
        "congestive heart failure with preserved ejection fraction",
        "development of hfpef",
        "diastolic and systolic function in vivo",
        "efficiency",
        "function",
        "functional effect",
        "functional improvement",
        "global lv work",
        "heart failure",
        "heart failure and its associated symptoms",
        "heart failure with a preserved ejection fraction",
        "heart failure with preserved ejection fraction (hfpef)",
        "heart failure with preserved ejection fraction (hfpef)/severe diastolic dysfunction",
        "heart failure with preserved ejection fraction phenotype",
        "heart function",
        "heart index",
        "hfpef",
        "hfpef onset",
        "hfpef phenotype",
        "hfpef phenotypes",
        "hfpef progression",
        "hfpef severity",
        "impaired cardiac reserves",
        "ischemia-reperfusion injury",
        "left ventricular diastolic and systolic function",
        "left ventricular function",
        "left ventricular function post-ppci",
        "left ventricular systolic and diastolic function",
        "left ventricular systolic and, particularly, diastolic function",
        "lv kc",
        "lv morphology and function",
        "lv stroke volume",
        "lv torsion",
        "lv, rv and coronary dysfunctions",
        "mitral regurgitation",
        "myocardial dysfunction",
        "myocardial injury",
        "myocardial performance index",
        "myocardial salvage",
        "pathological phenotype",
        "pef",
        "reduced ventricular function",
        "right heart dysfunction",
        "right ventricular dysfunction",
        "rv structure and function",
        "stroke volume",
        "stroke volume (sv)",
        "stroke volume, end-diastolic volume, and cellular arrhythmogenicity",
        "stroke work",
        "systolic and diastolic function of the heart by echocardiography",
        "systolic and diastolic radial velocities",
        "velocity",
        "ventricular atrophy, valve dysfunction, decreased cardiac output, and lowered stroke volumes",
        "ventricular wall movement",
    ],
    "cardiac_hypertrophy": [
        "biventricular hypertrophy",
        "cardiac cell size and abundance",
        "cardiac hypertrophic remodelling",
        "cardiac hypertrophy",
        "cardiac hypertrophy and fibrosis",
        "cardiac hypertrophy, ischemia, necrosis, and vasculitis",
        "cardiac mass",
        "cardiac wall thickening",
        "cardiomegaly",
        "cardiomyocyte cross sectional area",
        "cardiomyocyte cross-sectional area",
        "cardiomyocyte diameter",
        "cardiomyocyte hypertrophy",
        "cardiomyocyte hypertrophy and cardiac fibrosis",
        "cardiomyocyte hypertrophy and disordered arrangement",
        "cardiomyocyte hypertrophy and interstitial fibrosis",
        "cardiomyocyte size",
        "cell hypertrophy",
        "cm hypertrophy",
        "cm size",
        "concentric cardiac hypertrophy",
        "concentric left ventricular (lv) hypertrophy",
        "concentric lv hypertrophy",
        "concentric myocardial hypertrophy",
        "eccentric hypertrophy",
        "eccentric lv hypertrophy",
        "heart weight",
        "heart weight/body weight",
        "heart weight/body weight ratios",
        "hw/tl ratio",
        "hwi",
        "hypertrophied left ventricle",
        "hypertrophy",
        "hypertrophy and apoptosis",
        "increased left ventricular wall thickness",
        "interventricular septal thickness (ivst)",
        "interventricular septal wall thickness",
        "left atrial mass",
        "left ventricular (lv) concentric hypertrophy",
        "left ventricular (lv) hypertrophy",
        "left ventricular (lv) mass",
        "left ventricular (lv) wall thickness",
        "left ventricular anterior wall thickness",
        "left ventricular anterior/posterior wall (lvaw/lvpw)",
        "left ventricular hypertrophy",
        "left ventricular mass",
        "left ventricular posterior wall thickness",
        "left ventricular wall thickness",
        "lv hypertrophy",
        "lv hypertrophy, enlargement, and diastolic function",
        "lv mass",
        "lv mass index",
        "lv wall thickening",
        "lv wall thickness",
        "lv weight",
        "lv/tibial length (tl)",
        "mass",
        "muscle cross-sectional area",
        "myocardial hypertrophy",
        "myocardial hypertrophy (heart weight/tibia length)",
        "myocardial hypertrophy and fibrosis",
        "myocardial hypertrophy and fibrotic remodelling",
        "myocardial mass",
        "myocyte cross-sectional area",
        "myocyte hypertrophy",
        "myocyte size",
        "pathologic cardiac hypertrophy",
        "pathological hypertrophy",
        "reduced cardiac hypertrophy",
        "relative wall thickness",
        "rv and lv hypertrophy",
        "rv cardiomyocyte hypertrophy",
        "rv hypertrophy",
        "the thickness of the interventricular septum at the end of diastole (ivsd)",
        "the thickness of the posterior wall at the end of diastole (pwd)",
        "ventricular hypertrophy",
        "wall thickness",
        "wall-thickness",
    ],
    "calcium_handling": [
        "[ca2+]c transients and sarcomere shortening",
        "[ca2+]i transients amplitude",
        "[ca2+]i transients decay rate",
        "[ca2+]it",
        "amplitude of [ca2+]c transients and systolic sarcomere shortening",
        "amplitude of cs and cat",
        "arrhythmic spontaneous ca2+ release events (scaes)",
        "atrial cat amplitudes in vitro",
        "augmentation of cytosolic ca2+ release with increased stimulation frequency",
        "ca spark frequency",
        "ca2+ handling",
        "ca2+ handling properties",
        "ca2+ operational levels",
        "ca2+ release kinetics in nuclear cats",
        "ca2+ reuptake in cytosolic and nuclear cats",
        "ca2+ sensitivity",
        "ca2+ spark frequency",
        "ca2+ transient",
        "ca2+ transient (cat) amplitude",
        "ca2+ transient (cat) amplitudes",
        "ca2+ transient amplitude",
        "ca2+ transient decay",
        "ca2+ transient sarcoplasmic reticulum-ca2+ load",
        "ca2+ transients and cell contraction",
        "ca2+ transients and sarcomere shortening and relaxation in vitro",
        "ca2+-wave propagation",
        "caffeine-induced sarcoplasmic reticulum (sr) ca2+ release",
        "calcium handling",
        "calcium handling mechanisms",
        "calcium kinetics",
        "calcium re-uptake",
        "calcium release",
        "cardiomyocyte [ca2+] transient amplitude",
        "cardiomyocyte sr ca2+ leak",
        "cat",
        "cat amplitude",
        "cat amplitudes",
        "cat kinetics",
        "cats",
        "cytosolic ca2+ cycling",
        "cytosolic ca2+ transient amplitude",
        "cytosolic cat amplitudes",
        "decay half-times of the cytosolic ca2+ transients",
        "diastolic [ca2+ ]",
        "diastolic [ca2+]",
        "diastolic [ca2+] of cat",
        "diastolic and systolic mitochondrial ca2+ concentrations",
        "diastolic ca2+ and slowed ca2+ removal",
        "diastolic ca2+ decay through preactivated sarcoplasmic reticulum ca2+-atpase",
        "diastolic ca2+ levels",
        "early ca2+ release, amplitude, and prolonged the cat",
        "frequency of spontaneous ca2+ spark",
        "function of ca2+ handling proteins in lv cardiomyocytes",
        "local central cytosolic cat amplitude",
        "magnitude of scaes",
        "ncx forward mode activity (caffeine response)",
        "pro-arrhythmic diastolic sarcoplasmic reticulum (sr) ca2+ release",
        "pro-arrhythmogenic ca2+ sparks",
        "resting cytosolic ca2+ concentration",
        "reticulum-mitochondria ca2+ coupling",
        "sarcoplasmic reticulum (sr) ca2+ content",
        "sarcoplasmic reticulum (sr) ca2+ leak",
        "sarcoplasmic reticulum (sr) load",
        "soce",
        "sodium-calcium exchanger (ncx) forward-mode activity",
        "sr ca",
        "sr ca content",
        "sr ca leak",
        "sr ca2+ atpase activity",
        "sr ca2+ load",
        "subsarcolemmal cat amplitudes",
        "tetracaine-dependent sr ca leak",
    ],
    "fibrosis": [
        "activation of cardiac fibroblasts and myocardial fibrosis",
        "activation of human cardiac fibroblasts",
        "aortic fibrosis",
        "atrial fibrosis",
        "cardiac collagen content",
        "cardiac collagen deposition",
        "cardiac connective tissue content",
        "cardiac fibrosis",
        "cardiac fibrosis, hypertrophy, inflammation and hfpef",
        "cardiac fibrosis, macrophage infiltration, and gap junction remodeling",
        "cardiac fibrosis, steatosis, and diastolic dysfunction",
        "cardiorenal fibrosis",
        "cf",
        "collagen area fraction values",
        "collagen compaction",
        "collagen content",
        "collagen deposition",
        "collagen i/iii ratio",
        "collagen type i fibers",
        "collagen-rich fibrosis",
        "collagen/elastin ratio",
        "ecm-based stiffness",
        "excretion of collagen 1 and interleukin-6",
        "expression of myocardial carbonic anhydrase 9 and collagen",
        "extent of fibrosis",
        "extracellular matrix stiffness",
        "fibrosis",
        "fibrosis and inflammation",
        "fibrosis and pyroptosis",
        "fibrosis deposition",
        "fibrotic area",
        "fibrotic response",
        "histopathological findings of fibrotic/condensed collagen-deposition areas and apoptotic nuclei",
        "increased fibrosis in myocardium and kidney",
        "increased lv fibrosis",
        "interstitial collagen content",
        "interstitial fibrosis",
        "kidney fibrosis",
        "left ventricular fibrosis",
        "liver fibrosis",
        "lv collagen density",
        "lv fibrosis",
        "lv fibrosis and stiffening",
        "lv interstitial collagen fibrosis",
        "lv stiffening",
        "mild fibrosis",
        "mitochondrial damage and interstitial fibrosis",
        "myocardial collagen deposition",
        "myocardial fibrosis",
        "myocardial interstitial fibrosis",
        "myocardial perivascular collagen content",
        "myocardial volume and fibrosis area",
        "percentage of area of subendocardial fibrosis",
        "percentage of fibrosis",
        "perivascular fibrosis",
        "perivascular/interstitial fibrosis",
        "reparative fibrosis",
        "replacement fibrosis",
        "right ventricular fibrosis",
        "subendocardial fibrosis",
        "subendocardial left ventricular fibrosis",
        "tissue fibrosis",
        "tubule-interstitial fibrosis",
        "ventricular fibrosis and remodeling",
    ],
    "systolic_function": [
        "-dp/dt max",
        "atrial ejection fraction",
        "cardiac contractility",
        "cardiac ejection fraction",
        "cardiac systolic function",
        "change in ejection fraction",
        "dp/dt",
        "ef",
        "ef1",
        "ejection fraction",
        "ejection fraction (ef)",
        "ejection fractions",
        "end-systolic pressure-volume relationship",
        "fractional shortening",
        "fractional shortening (fs)",
        "free wall longitudinal fractional shortening",
        "fs",
        "heart contractility",
        "indices of systolic function",
        "inotropic reserve",
        "inotropic response to beta-adrenergic stimulation",
        "left atrial ejection fraction (laef)",
        "left ventricle ejection fraction",
        "left ventricular (lv) ejection fraction",
        "left ventricular (lv) fractional shortening",
        "left ventricular ejection fraction",
        "left ventricular ejection fraction (ef)",
        "left ventricular ejection fraction(lvef)",
        "left ventricular fractional shortening",
        "left-ventricular ejection fraction (lvef) level",
        "left-ventricular-ejection fraction (lvef)",
        "left-ventricular-fraction-shortening (lvfs)",
        "lv contractile function",
        "lv contractility of ees",
        "lv ejection fraction",
        "lv ejection fraction %",
        "lv ejection fraction (ef)",
        "lv fractional shortening",
        "lv peak +dp/dt",
        "lvef",
        "maximum rate of pressure rise",
        "peak positive first derivative of left ventricular pressure (dp/dtmax)",
        "percent increase in the left ventricular ejection fraction [lvef] after the isoproterenol challenge",
        "preserved ef",
        "preserved ejection fraction",
        "preserved systolic function",
        "preserved systolic performance",
        "regional peak fractional shortening",
        "resting lvef",
        "rv ejection fraction",
        "rv fractional area change",
        "subclinical systolic dysfunction",
        "systolic dysfunction",
        "systolic dysfunction by invasive hemodynamic analysis",
        "systolic function",
        "systolic function indexes",
        "systolic performance",
        "systolic performance parameters",
    ],
    "electrophysiology": [
        "action potential duration",
        "action potential remodeling",
        "action potentials",
        "af inducibility",
        "af susceptibility",
        "apd prolongation",
        "arrhythmias in cardiac myocytes",
        "arrhythmogenic changes",
        "arrhythmogenicity index",
        "atrial fibrillation inducibility",
        "cardiac alternans",
        "cardiomyocyte electrophysiology",
        "cellular arrhythmias",
        "corrected qt interval",
        "delay of repolarization",
        "delayed afterdepolarizations",
        "electrical conduction",
        "electrocardiogram parameters",
        "frequency of delayed afterdepolarizations",
        "heart blocks",
        "implantable cardioverter-defibrillator (icd) implantation rates",
        "inward rectifier potassium current (ik1)",
        "l-type ca2+ channel (ltcc) currents",
        "late na+ current",
        "left ventricle (lv) rr",
        "occurrence of af",
        "occurrence of ventricular arrhythmias",
        "pathological apd changes",
        "pr interval",
        "proarrhythmogenic action potential changes",
        "propagation of action potentials across the lv epicardium",
        "qrs complex",
        "qrs duration",
        "qrs prolongation",
        "qt interval",
        "qt interval duration",
        "qt prolongation and in vivo arrhythmia susceptibility",
        "qtc intervals",
        "rapid components of the delayed rectifier potassium current (ikr)",
        "rate of premature ventricular contractions",
        "san recovery time",
        "short-term variability of action potential duration (apd)",
        "spontaneous va",
        "susceptibility to va",
        "susceptibility to vas",
        "susceptibility to ventricular arrhythmias",
        "t-wave inversion",
        "transient outward potassium current (ito)",
        "transient outward potassium current density",
        "ventricular arrhythmias",
        "ventricular tachycardia incidence",
    ],
    "oxidative_stress": [
        "4-hydroxy-trans-2-nonenal",
        "4-hydroxynonenal (4-hne)",
        "4hne adducts",
        "a decreased pro-oxidative but increased anti-oxidant capacity",
        "activity of antioxidant defenses (cardiac superoxide dismutase)",
        "aortic o2 \u2022-production",
        "cardiac oxidative stress",
        "decreased anti-oxidant capacity",
        "dna oxidative damage",
        "enos and oxidative stress",
        "gsh/gssg ratio",
        "increased oxidative stress",
        "intracellular and mitochondrial reactive oxygen species",
        "intracellular ferrous ion, mda, and 4-hne levels",
        "lv superoxide production",
        "malondialdehyde",
        "malondialdehyde levels",
        "markers of oxidative and nitrosative stress",
        "markers of oxidative stress and dna damage/senescence in the microvascular endothelium",
        "mitochondrial h2o2 emission",
        "mitochondrial oxidative stress",
        "mitochondrial reactive oxygen species",
        "mitochondrial reactive oxygen species (ros)",
        "mitochondrial reactive oxygen species and mir-193b levels",
        "mitochondrial ros",
        "mitochondrial ros production",
        "mitochondrial-derived reactive oxygen species (ros) generation",
        "mt-ros",
        "mt-ros production",
        "myocardial malonaldehyde level",
        "myocardial oxidative stress and apoptosis",
        "nitro-oxidative stress",
        "oxidative and nitrosative stress",
        "oxidative and nitrosative stress markers, hydrogen peroxide, and 3-nitrotyrosine",
        "oxidative stress",
        "oxidative stress, hypertrophy, and the onset and progression of hfpef",
        "oxidized dyhydroethidium",
        "oxidized glutathione",
        "oxidized low-density lipoprotein (ox-ldl)",
        "pro-inflammatory and oxidative stress markers",
        "production of reactive oxygen species and lipid peroxidation",
        "rate of extracellular hydrogen peroxide consumption and peroxidatic activity",
        "reactive oxygen species (ros) production",
        "reactive oxygen species and apoptosis",
        "reactive oxygen species generation",
        "reactive oxygen species levels",
        "ros",
        "ros emission",
        "serum malondialdehyde (mda) concentration",
        "superoxide anion",
        "vascular advanced glycation end products, nf-\u03bab, and nitrotyrosine levels",
    ],
    "hemodynamics": [
        "average hemodynamic forces",
        "baseline in vivo hemodynamics",
        "central venous pressure",
        "edp",
        "edp/edv ratio",
        "elevated end diastolic pressure (edp)",
        "elevated lv end-diastolic pressures",
        "end diastolic pressure",
        "end-diastolic pressure",
        "end-diastolic pressure (edp)",
        "end-diastolic pressure at afterload increase",
        "end-diastolic pressure/end-diastolic volume (edp/edv) ratio",
        "end-diastolic pressures",
        "estimated atrial pressures",
        "exercise hemodynamic responses to \u03b2-blockers",
        "exercise hemodynamics (cardiac output, heart rate and pulmonary capillary wedge pressure)",
        "exercise pulmonary hypertension",
        "filling pressure",
        "hemodynamic assessment",
        "hemodynamic force root mean square (rms) values",
        "hemodynamics",
        "left atria filling pressures",
        "left atrial pressure",
        "left ventricular end diastolic pressure (lvedp)",
        "left ventricular end diastolic pressures",
        "left ventricular end-diastolic pressure",
        "left ventricular end-diastolic pressure (lvedp)",
        "left ventricular filling pressure",
        "left ventricular filling pressures",
        "left ventricular systolic pressure",
        "lv end-diastolic pressure",
        "lv end-diastolic pressure (lvedp)",
        "lv end-diastolic pressures",
        "lv filling pressure",
        "lvedp",
        "mean and maximum systolic pressure",
        "mean lv end-diastolic",
        "peak pressure",
        "pressure gradient across the aortic constriction",
        "pulmonary capillary wedge pressure",
        "pulmonary capillary wedge pressures",
        "ratio between hemodynamic forces in the inferolateral-anteroseptal and apical-basal direction",
        "resting levels of csna",
        "right and left ventricular hemodynamics",
        "right ventricle-pulmonary artery coupling",
        "rv pressure overload",
        "surrogate markers of rv overload (e.g., higher mean and maximum systolic pressure)",
        "systemic blood pressure",
        "ventricular-arterial coupling ratio",
        "wall stress",
    ],
    "histological_changes": [
        "alveolar-capillary membrane thickening",
        "aortic endothelial cell coverage",
        "aortic media thickening",
        "basement membrane thickening",
        "cardiac lymphatic integrity",
        "cardiac structure",
        "cardiomyocyte structure, sarcomeric assembly, and stability",
        "connexin 43",
        "connexin 43 lateralization",
        "connexin 43 staining",
        "deposition of proteinaceous material in the tubules",
        "ecv",
        "fibre type shift from fast-to-slow twitch",
        "fluid and protein loss in pulmonary interstitium",
        "ihc staining",
        "immunofluorescence staining of n-cadherin and vinculin",
        "infarct area",
        "infarct size",
        "infarct size/ischaemic area at risk",
        "intestinal epithelial barrier damage",
        "junction proteins in the endothelial barrier and between cardiomyocytes",
        "lec numbers and marker expression levels",
        "loss of sarcomere content",
        "lung injury",
        "lv infarct scar size",
        "lysosomal disruption",
        "mash and metald",
        "masson's and h&e stainings",
        "mi size",
        "multiorgan histopathology",
        "myocardial ferritin",
        "myocardial histomorphological lesions",
        "myocardial pathology",
        "myocardial structural damage",
        "myocardial ultrastructure",
        "organelle density",
        "oxidative stress-exposed area within the heart",
        "parenchymal pulmonary destruction",
        "pericardial thickening",
        "perivascular fluid cuff formation around extra-alveolar vessels",
        "sarcomeric disorganization",
        "t-tubule structure",
        "t-tubule tt-sr microstructural remodeling",
        "t1 modified look-locker inversion recovery values",
        "titin hyperphosphorylation",
        "titin phosphorylation at s4099 and hyperphosphorylation at s11878",
        "ultrastructural damage",
        "zonula occludens protein density",
    ],
    "cardiac_morphology": [
        "atrial enlargement",
        "atrial size in vivo",
        "atrial weight",
        "cardiac geometry",
        "cardiac morphometry",
        "chamber sizes",
        "dilatation of the left ventricle",
        "end diastolic volume",
        "end systolic volume",
        "end-diastolic volume",
        "end-systolic volume",
        "enlarged left ventricle",
        "la area",
        "la enlargement",
        "lasi",
        "left atrial (la) anteroposterior diameter",
        "left atrial (la) enlargement",
        "left atrial (la) enlargement and dysfunction",
        "left atrial (la) size",
        "left atrial area",
        "left atrial diameter",
        "left atrial dilatation",
        "left atrial enlargement",
        "left atrial volume",
        "left ventricular dilatation",
        "left ventricular end-diastolic diameter",
        "left ventricular end-systolic volume",
        "left ventricular internal diameter in diastole and systole",
        "lung and lv weights",
        "lv and lung weight",
        "lv and lung weight corrected by tibial length",
        "lv and lung weights",
        "lv diastolic volume",
        "lv dilation",
        "lv dimensions",
        "lv end-diastolic dimension",
        "lv end-diastolic volume",
        "lvedd",
        "lvesd",
        "mi size as % of aar",
        "myocardial fractional volume",
        "rv dilatation",
        "smaller hearts",
        "structural echocardiographic parameters",
        "ventricular dilation",
    ],
    "mitochondrial_function": [
        "cardiac mitochondrial basal respiration",
        "cardiac mitochondrial content",
        "cardiac mitochondrial fatty acid oxidation",
        "cardiac mitochondrial fatty-acid metabolism",
        "cardiac mitochondrial respiratory function",
        "complex ii abundance",
        "heart mitochondrial dna levels",
        "impaired in situ mitochondrial respiration",
        "inner mitochondrial membrane potential",
        "levels of several mitochondrial electron transport chain proteins from complexes i, ii, iii and v",
        "maximal mitochondrial respiration",
        "mitochondria respiration",
        "mitochondria were less polarized",
        "mitochondrial and functional impairments in both the diaphragm and soleus",
        "mitochondrial biogenesis",
        "mitochondrial ca2+ buffer capacity",
        "mitochondrial ca2+ concentration",
        "mitochondrial ca2+ overload",
        "mitochondrial calcium retention capacity",
        "mitochondrial complex activity",
        "mitochondrial content",
        "mitochondrial dysfunction",
        "mitochondrial dysfunction, impaired atp production, inflammation, and reduced cardiac mass",
        "mitochondrial function",
        "mitochondrial function (mainly in complex iv)",
        "mitochondrial impairments",
        "mitochondrial integrity",
        "mitochondrial mass and numbers, and enhanced mitochondrial respiration",
        "mitochondrial oxidative phosphorylation",
        "mitochondrial oxygen consumption rate (ocr)",
        "mitochondrial permeability transition pore",
        "mitochondrial respiration",
        "mitochondrial respiratory capacity",
        "mitochondrial respiratory complex activities",
        "mitochondrial respiratory function",
        "mitochondrial supercomplexes",
        "mptp opening",
        "oxygen consumption rate (ocr)",
        "skeletal muscle mitochondrial respiration",
        "susceptibility to opening of the mitochondrial permeability transition pore (mptp)",
        "synthesis of mitochondrial respiratory chain complexes i + ii",
        "tfam/nrf1-mediated mitochondrial biogenesis disorder",
        "vmax complex iv",
    ],
    "inflammation": [
        "activated t cells and increased mhc iilow macrophage infiltration",
        "advanced glycation end products and nf-\u03bab levels",
        "advanced glycation end products, nf-\u03bab, and nitrotyrosine levels",
        "cardiac inflammation",
        "cardiac inflammation and hypertrophy",
        "cardiac inflammation and reactive oxygen species (ros) production",
        "cardiac macrophage invasion",
        "cardiac macrophage phenotypic shifts",
        "cardiac vasculitis",
        "cardiac-renal inflammation",
        "cd68 counts",
        "decreased s100a9-positive macrophage infiltration",
        "density of infiltrating cardiac immune cells",
        "elevated inflammatory cytokines",
        "inflammation",
        "inflammation and cardiac hypertrophy",
        "inflammation and fibrosis",
        "inflammatory cell infiltration in myocardium",
        "inflammatory chemokines and cytokines response",
        "inflammatory cytokine levels",
        "inflammatory cytokines",
        "inflammatory infiltrate",
        "lv inflammatory cell infiltration",
        "m2-macrophage population",
        "macrophage accumulation in visceral adipose tissue",
        "macrophage infiltration",
        "macrophage infiltration in left ventricular tissue",
        "macrophage polarization",
        "myocardial inflammation",
        "myocardial inflammation, fibrosis, cardiomyocyte apoptosis, oxidative stress",
        "myocardial levels of pro-inflammatory cytokines (tnf-\u0315\u0375\u0311\u0364\u0300\u0301\u0302\u0303\u0304\u0305\u0306\u0307\u0308\u0309\u030a\u030b\u030c\u030d\u030e\u030f\u0310\u0311\u0312\u0313\u0314\u0315\u0316\u0317\u0318\u0319\u031a\u031b\u031c\u031d\u031e\u031f\u0320\u0321\u0322\u0323\u0324\u0325\u0326\u0327\u0328\u0329\u032a\u032b\u032c\u032d\u032e\u032f\u0330\u0331\u0332\u0333\u0334\u0335\u0336\u0337\u0338\u0339\u033a\u033b\u033c\u033d\u033e\u033f\u0340\u0341\u0342\u0343\u0344\u0345\u0346\u0347\u0348\u0349\u034a\u034b\u034c\u034d\u034e\u034f\u0350\u0351\u0352\u0353\u0354\u0355\u0356\u0357\u0358\u0359\u035a\u035b\u035c\u035d\u035e\u035f\u0360\u0361\u0362\u0363\u0364\u0365\u0366\u0367\u0368\u0369\u036a\u036b\u036c\u036d\u036e\u036f\u0371\u0371\u0373\u0373\u0374\u0375\u0377\u0377\u0378\u0379\u037a\u037b\u037c\u037d\u037e\u03f3\u0380\u0381\u0382\u0383\u0384\u0385\u03ac\u0387\u03ad\u03ae\u03af\u038b\u03cc\u038d\u03cd\u03ce\u0390\u03b1\u03b2\u03b3\u03b4\u03b5\u03b6\u03b7\u03b8\u03b9\u03ba\u03bb\u03bc\u03bd\u03be\u03bf\u03c0\u03c1\u03a2\u03c3\u03c4\u03c5\u03c6\u03c7\u03c8\u03c9\u03ca\u03cb\u03ac\u03ad\u03ae\u03af\u03b0\u03b1\u03b2\u03b3\u03b4\u03b5\u03b6\u03b7\u03b8\u03b9\u03ba\u03bb\u03bc\u03bd\u03be\u03bf\u03c0\u03c1\u03c2\u03c3\u03c4\u03c5\u03c6\u03c7\u03c8\u03c9\u03ca\u03cb\u03cc\u03cd\u03ce\u03d7\u03d0\u03d1\u03d2\u03d3\u03d4\u03d5\u03d6\u03d7\u03d9\u03d9\u03db\u03db\u03dd\u03dd\u03df\u03df\u03e1\u03e1\u03e3\u03e3\u03e5\u03e5\u03e7\u03e7\u03e9\u03e9\u03eb\u03eb\u03ed\u03ed\u03ef\u03ef\u03f0\u03f1\u03f2\u03f3\u03b8\u03f5\u03f6\u03f8\u03f8\u03f2\u03fb\u03fb\u03fc\u037b\u037c\u037da, il-6 and ccl2)",
        "nlr family pyrin domain containing 3 (nlrp3)/gsdmd pyroptosis in eat",
        "number of pro-inflammatory macrophages",
        "overproduction of il (interleukin)-1\u03b2/il-18",
        "p2x7-nlrp3 inflammasome activation",
        "populations of macrophages and myofibroblasts in the myocardium",
        "presence of pro-inflammatory cardiac fibroblasts",
        "preventing m1 macrophage polarization",
        "proinflammatory ly6chi ccr2+ macrophages",
        "recruitment of classical monocytes",
    ],
    "protein_phosphorylation": [
        "adrenergic pka (protein kinase a)-dependent phosphorylation of troponin-i",
        "ampk\u03b1 phosphorylation",
        "camkii expression in its active phosphorylated form",
        "cardiac levels of phosphoproteins involved in ... the krebs cycle (malate dehydrogenase and aspartate aminotransferase)",
        "cardiac levels of phosphoproteins involved in the pentose phosphate pathway (ppp) (6-phosphogluconolactonase and 6-phosphogluconate dehydrogenase)",
        "cardiac myosin binding protein c and cardiac troponin i phosphorylation",
        "dynamin-related protein 1 phosphorylation at s637",
        "hyperphosphorylation of ryr2 at ser2814",
        "hyperphosphorylation of titin",
        "myofibrillar protein phosphorylation",
        "myofilament protein expression and phosphorylation",
        "pdh phosphorylation",
        "pevk element phosphorylation",
        "phospholamban phosphorylation at s16",
        "phosphoproteome",
        "phosphorylated phospholamban",
        "phosphorylated protein residues",
        "phosphorylation level",
        "phosphorylation level of titin (n2b)",
        "phosphorylation levels of c-raf, mek1/2, and erk1/2",
        "phosphorylation levels of cardiac troponin i and myosin binding protein-c",
        "phosphorylation levels of mitogen-activated protein (map) kinases such as c-raf, mek1/2, and extracellular signal-regulated kinase 1/2 (erk1/2)",
        "phosphorylation levels of smad (smad2 and smad3) and mapk (c-raf, erk1/2) pathway proteins",
        "phosphorylation of camkii expression",
        "phosphorylation of cardiac myosin-binding protein c (ser282 cmybp-c)",
        "phosphorylation of downstream mtorc1 effectors",
        "phosphorylation of phospholamban and mammalian target of rapamycin",
        "phosphorylation of pka sites in the n2b element",
        "phosphorylation of plb at thr17",
        "phosphorylation of titin's pevk and n2b spring elements",
        "phosphorylation of troponin i (ser23, 24 tni)",
        "phosphorylation state of titin",
        "pln phosphorylation",
        "protein and phosphorylated ser, thr, and tyr residues",
        "smad3 phosphorylation",
        "titin phosphorylation",
        "titin phosphorylation pattern",
        "total titin phosphorylation",
        "troponin-i phosphorylation",
        "vasp phosphorylation",
    ],
    "renal_function": [
        "24-hour urinary protein excretion",
        "albuminuria",
        "blood urea nitrogen [bun]",
        "creatinine",
        "creatinine level",
        "creatinine-corrected homoarginine excretion",
        "fecal k+ excretion",
        "fractional excretion of electrolytes",
        "glomerular filtration rate",
        "glomerular filtration rate (gfr)",
        "markers of kidney damage",
        "markers of renal damage",
        "plasma k+ elevation",
        "plasma k+ response",
        "proteinuria",
        "renal blood flow",
        "renal function",
        "renal injury",
        "renal medullary oxygenation",
        "serum creatinine",
        "serum creatinine (scr)",
        "serum osmolality",
        "tubular injury",
        "urinary creatinine concentration",
        "urinary k+ excretion",
        "urinary protein/creatinine ratio",
        "urine albumin creatinine ratio",
    ],
    "natriuretic_peptides": [
        "atrial natriuretic peptide (anp) levels",
        "b-type natriuretic peptide",
        "b-type natriuretic peptide (bnp)",
        "bnp",
        "bnp level",
        "bnp levels",
        "brain natriuretic peptide levels",
        "cardiac and plasma anp and bnp expression",
        "cardiac expression of brain natriuretic peptide",
        "elevated natriuretic peptides",
        "elevated nt-probnp plasma levels",
        "heart failure (brain natriuretic peptide (bnp) levels",
        "left ventricular brain natriuretic peptide levels",
        "mean plasma bnp concentrations",
        "myocardial bnp",
        "myocardial pro-brain natriuretic peptide protein abundance",
        "n-terminal pro-beta-type natriuretic peptide (nt-pro-bnp) levels",
        "natriuretic peptide levels",
        "natriuretic peptides",
        "nt-probnp",
        "plasma brain natriuretic peptide concentration",
        "plasma brain natriuretic peptide decrease",
        "plasma brain natriuretic peptide levels",
        "plasma levels of anp and its cardiac expression",
        "plasma nt-probnp",
        "plasma nt-probnp levels",
    ],
    "myocardial_strain": [
        "abnormal myocardial strain",
        "circumferential strain",
        "global longitudinal strain",
        "global longitudinal strain (gls)",
        "global peak circumferential strain",
        "gls",
        "gls parameters",
        "la reservoir, conduit, and contractile strain",
        "lasr",
        "left ventricle peak diastolic strain rate",
        "longitudinal strain",
        "longitudinal strain rate (lsr)",
        "lsr",
        "lv circumferential strain",
        "lv global longitudinal strain",
        "lv strain",
        "myocardial deformation",
        "myocardium strain",
        "peak longitudinal strain rate",
        "peak longitudinal strain rate during early filling (peak reverse longitudinal strain rate)",
        "reverse longitudinal strain rate",
        "reverse peak longitudinal strain",
        "strain",
        "strain abnormalities indicative of contraction-relaxation cycle impairment",
        "strain dysfunction",
    ],
    "exercise_capacity": [
        "effort intolerance",
        "effort tolerance",
        "effort tolerance and v\u0307o 2 max",
        "endurance capacity",
        "exercise capacity",
        "exercise endurance",
        "exercise exhaustion",
        "exercise intolerance",
        "exercise performance",
        "exercise tolerance",
        "exercise tolerance in treadmill testing",
        "exercise tolerance on a treadmill",
        "impaired exercise capacity",
        "low exercise capacity",
        "maximum o2 consumption",
        "maximum workload",
        "physical endurance",
        "reduced exercise capacity",
        "reduced exercise tolerance",
        "running distance",
        "treadmill exercise",
        "vo2max",
        "voluntary running distances",
        "v\u0307o2max",
    ],
    "apoptosis": [
        "annexin-v",
        "apoptosis",
        "apoptosis in the myocardium",
        "apoptotic [mitochondrial-bax/cleaved-caspase-3/cleaved-poly (adp-ribose) polymerase]",
        "apoptotic activity",
        "apoptotic reaction",
        "bcl-2/bax ratio",
        "bcl2-associated x (bax)",
        "biomarkers of cardiomyocyte apoptosis",
        "cardiac apoptosis",
        "cardiomyocyte apoptosis",
        "cardiomyocyte death",
        "caspase 3 activity",
        "caspase 9",
        "caspase-3 levels",
        "cell death",
        "cleaved caspase-3",
        "cytochrome c levels",
        "h9c2 cell death",
        "myocyte apoptosis",
        "number of apoptotic nuclei",
        "renal cortical caspase 8",
        "tunel-positive cells",
    ],
    "microvascular_density": [
        "capillarity",
        "capillary density",
        "capillary diameter",
        "capillary-to-fibre ratio",
        "cardiac capillary density",
        "cardiac mv density",
        "cardiac vascular density",
        "cd31",
        "cerebrovascular regression",
        "coronary microvascular rarefaction",
        "cortical mv density",
        "density of capillary",
        "heart capillary density",
        "heart microvasculature",
        "microvascular density",
        "microvascular rarefaction",
        "myocardial capillary density",
        "myocardial microvascular density",
        "number and coverage rate of cardiac pericytes",
        "peritubular capillary density",
        "pulmonary vascular density",
        "small-vessel number",
        "vascular density",
    ],
    "stiffness": [
        "cardiomyocyte passive stiffness",
        "cardiomyocyte stiffness",
        "cellular diastolic stiffness",
        "echocardiographic parameters of impaired left ventricular (lv) stiffness",
        "in vitro stiffness",
        "increased lv stiffness",
        "left ventricular chamber stiffness",
        "left ventricular stiffness",
        "lv chamber stiffness",
        "lv stiffness",
        "myocardial stiffness",
        "passive cardiomyocyte stiffness",
        "passive filling stiffness",
        "passive stiffness",
        "passive tension",
        "resting stiffness",
        "sarcomere length-passive tension relationship",
        "stiffness",
        "stiffness (fpassive)",
        "stiffness coefficient of end-diastolic pressure-volume relation (edpvr)",
        "stiffness parameters [formula: see text] and [formula: see text]",
        "tissue stiffening",
        "titin-based muscle stiffness",
    ],
    "cardiac_remodeling": [
        "adverse cardiac remodeling by increasing the ratio of the more compliant collagen type 3 to that of the more tensile collagen type 1 in the heart",
        "adverse left ventricular remodeling",
        "atrial remodeling",
        "cardiac modeling (inflammation, interstitial fibrosis, and hypertrophy)",
        "cardiac remodeling",
        "cardiac remodeling and diastolic dysfunction",
        "cardiac remodelling",
        "cardiac remodelling and diastolic function",
        "concentric remodeling",
        "detrimental interstitial matrix remodeling",
        "fibrotic remodeling",
        "fibrotic remodelling",
        "hypertrophic and fibrotic remodelling",
        "hypertrophic and fibrotic remodelling of the myocardium",
        "left ventricle concentric remodeling",
        "left ventricular (lv) concentric remodeling",
        "left ventricular concentric remodeling",
        "left ventricular remodeling",
        "left ventricular remodelling",
        "myocardial remodeling",
        "myocardial structural remodeling and function",
        "ventricular remodeling",
    ],
    "contractility": [
        "cardiomyocyte contractile and relaxation performance",
        "cardiomyocyte mechanics and contractility",
        "cardiomyocyte shortening",
        "cardiomyocytes were hypercontractile",
        "cell shortening",
        "cell shortening amplitude",
        "cellular contractility",
        "contractile function",
        "contractile kinetics",
        "contractile reserve",
        "contractile reserves",
        "contraction and relaxation velocities",
        "depressed contractile responses",
        "development of maximum force",
        "dl/dtmax",
        "force development",
        "force production",
        "half-widths of the contractile responses",
        "myocyte contraction (dl/dtmax)",
        "sarcomere function",
        "sarcomere shortening",
        "shortening amplitude",
    ],
    "glucose_metabolism": [
        "24-hour urinary glucose excretion",
        "blood glucose",
        "fasting glucose",
        "glucose",
        "glucose handling",
        "glucose intolerance",
        "glucose metabolism",
        "glucose oxidation",
        "glucose tolerance",
        "glycaemia",
        "glycemic indices",
        "glycemic regulation",
        "hba1c",
        "hba1c levels",
        "hyperglycemia",
        "impaired glucose handling",
        "impaired glucose tolerance",
        "oral glucose tolerance",
        "plasma blood glucose",
        "plasma glucose and insulin levels",
        "serum glucose",
        "systemic glucose metabolism",
    ],
    "inflammatory_markers": [
        "il-10",
        "il-1\u03b2",
        "il-2",
        "il-4",
        "il-6 plasma levels",
        "inflammatory marker, crp",
        "inflammatory markers",
        "interferon-\u03b3",
        "interleukin (il)-1\u03b2",
        "interleukin 1\u03b2",
        "interleukin-1 beta (il-1\u03b2)",
        "interleukin-6 (il-6)",
        "interleukin-8 (il-8)",
        "lps",
        "plasma concentrations of circulating cytokines",
        "plasma il-18 levels",
        "plasma levels of soluble suppression of tumorigenicity-2, interleukin-1\u03b2,-6 and-17a",
        "plasma os markers and levels of profibrotic and proinflammatory cytokines",
        "serum crp levels",
        "tnf-\u03b1",
        "tumor necrosis factor (tnf)-\u03b1",
        "tumor necrosis factor \u03b1 (tnf\u03b1)",
    ],
    "signaling_pathway": [
        "activation of c-jun n-terminal protein kinase (jnk)",
        "activation of p2x7/nlrp3 signaling",
        "activation of pi3/akt pathway",
        "activation of wnt-\u03b2-catenin signaling",
        "akt and nos isoform expression and phosphorylation",
        "ampk activity",
        "cgas-sting signaling",
        "decreased apn-mediated coronary angiogenesis, along with increased circulatory apn levels and decreased cardiac apn signaling (index of apn resistance)",
        "fibrotic (transforming-growth factor-\u00df/phosphorylated-smad3)",
        "increased activation of 6 of 8 proteins from the egfr/igfr1 cluster in hcm",
        "jnk activation",
        "levels of transforming growth factor beta 1 and smad2/3",
        "nf-\u03bab",
        "nf\u03bab",
        "pathological signalling cascades",
        "pi3k/akt pathway",
        "pkg activation",
        "protein kinase a activation",
        "protein kinase g signaling",
        "renin-angiotensin-aldosterone system",
        "tgf-\u03b2/smad3/ctgf signaling",
    ],
    "blood_pressure": [
        "aortic pressure (aop)",
        "arterial blood pressure",
        "arterial hypertension",
        "blood pressure",
        "blood pressure (bp)",
        "blood pressure elevation",
        "blood pressures",
        "bp increase",
        "hypertension",
        "increased pulmonary pressure",
        "mean arterial pressure",
        "pulmonary arterial systolic pressure",
        "pulmonary artery pressure",
        "pulmonary hypertension",
        "pulmonary pressures",
        "rv systolic pressure",
        "systemic arterial pressures",
        "systemic blood pressure levels",
        "systemic hypertension",
        "systolic blood pressure",
    ],
    "biomarkers": [
        "b-type natriuretic peptide (bnp) level",
        "cellular expressions of dna-damage/heart-failure (\u03b3-h2ax+//xrcc1+cd90+//bnp+) biomarkers",
        "circulating biomarkers",
        "circulating markers of inflammation and fibrosis",
        "circulating markers of tissue damage",
        "exosomes' level",
        "expression levels of diagnostic biomarkers",
        "heart failure marker levels",
        "osteopontin plasma levels",
        "plasma activity and level of fap",
        "plasma levels of gal-3 and timp-1",
        "plasma levels of gal-3, gdf-15 and timp1",
        "plasma levels of timp-1 and gdf-15",
        "plasma tnc levels",
        "serum cardiac troponin levels",
        "serum ck-mb (u/l)",
        "serum ferritin level",
        "serum injury biomarkers",
        "systemic cardiovascular injury markers",
    ],
    "lipid_profile": [
        "blood triglycerides",
        "cardiac lipidome",
        "cardiolipin",
        "ceramide, cholesterol, and other lipids",
        "cholesterol",
        "dyslipidemia",
        "free fatty acid content",
        "glycerophospholipids, cholesterol, and cholesteryl esters while increasing triglyceride levels in cardiac tissue",
        "lipid deposition",
        "lipid disorders",
        "lipid profiles",
        "lipids",
        "myocardial lipid disturbance and cardiac phenotypes",
        "myocardial lipids",
        "plasma cholesterol",
        "plasma triglycerides",
        "serum cholesterol and triglycerides",
        "triglycerides",
        "triglycerides and diglycerides",
    ],
    "metabolite_levels": [
        "amino acid accumulation",
        "arginine",
        "cardiac levels of key metabolites of the ppp such as 6-phosphogluconate, d-ribose 5-phosphate, and arginine",
        "cardiovascular sulphur bioavailability",
        "carnitine",
        "citrulline",
        "fructose-2,6-biphosphate",
        "homoarginine",
        "ipa levels",
        "iron",
        "key metabolites, including l-lysine, d-glucose, and uridine",
        "levels of indole-3-propionic acid (ipa)",
        "lysine",
        "nad+/nadh",
        "nadph",
        "nicotinamide",
        "ornithine",
        "sdma",
        "tmao",
    ],
    "vascular_function": [
        "aortic vascular function",
        "capacity to drain fluids and immune cells",
        "coronary calcium",
        "exercise hyperaemia",
        "hindlimb blood flow",
        "hyperemic flow",
        "impaired vascular function",
        "markers for aortic valve sclerosis",
        "microvascular impairment",
        "microvascular obstruction",
        "myocardial blood volume",
        "pa functional impairment",
        "perfusion",
        "reduced arterial flow",
        "resting coronary flow",
        "resting flow",
        "vascular dysfunction",
        "vascular smooth muscle and endothelial function",
    ],
    "myofilament_function": [
        "active and passive tension",
        "calcium-activated tension",
        "cardiomyocyte passive tension",
        "compliance of titin",
        "cross-bridge cycling",
        "cross-bridge cycling kinetics",
        "crossbridge attachment and detachment rates at matched tension",
        "myofilament ca2+ affinity",
        "myofilament ca2+ sensitivity",
        "myofilament relaxation",
        "myofilament sensitivity",
        "rate constant of tension redevelopment (ktr)",
        "rate of the actin-myosin cross-bridge cycle",
        "tension cost",
        "tension development",
        "titin compliance",
        "titin-based passive tension",
    ],
    "protein_modification": [
        "akt s-nitrosylation",
        "detyrosinated \u03b1-tubulin",
        "hyperacetylation of cardiac proteins",
        "hyperbutyrylation of succinate-coa ligase subunit alpha (suclg1) at k90",
        "inhibitory lysine acetylation of the pyruvate dehydrogenase (pdh) complex",
        "lactylation scores",
        "mitochondrial hyperacetylation",
        "mitochondrial protein glycation",
        "p53 acetylation",
        "parkin recruitment and polyubiquitination of voltage-dependent anion channel 1",
        "protein acetylation",
        "protein hyperacetylation",
        "s-nitrosylation",
        "total muscle protein ubiquitination",
        "tubulin detyrosination",
        "ubiquitin localization",
    ],
    "metabolic_parameters": [
        "blood glucose, fatty acids, and ketone body levels",
        "circulating levels of cholesterol and sodium",
        "food intake",
        "fructose and alcohol consumption",
        "hypercholesterolemia",
        "metabolic parameters",
        "metabolic profiles",
        "metabolic state",
        "oxygen consumption",
        "peak oxygen consumption",
        "respiratory exchange ratio",
        "respiratory quotient",
        "respiratory quotient during exercise",
        "standardized uptake value",
    ],
    "metabolism": [
        "bcaa catabolic activities",
        "capacity for \u0320-hydroxybutyrate oxidation",
        "downregulation of metabolic networks involved in oxidative phosphorylation, substrate transport, and energy production",
        "endothelial cell glycolytic function",
        "fat oxidation",
        "fatty acid oxidation",
        "fatty acid oxidation capacity",
        "fatty acid \u0322-oxidation",
        "ketone oxidation rates",
        "krebs cycle during beta-adrenergic stimulation",
        "lipid and ketone metabolism",
        "metabolic dysregulation with inflammation",
        "oxidizing pyridine nucleotides",
        "substrate utilization",
    ],
    "energy_metabolism": [
        "atp levels",
        "atp levels and stabilizing mitochondrial membrane potential",
        "atp production",
        "atp synthesis",
        "atp/adp ratio",
        "energy expenditure",
        "energy metabolism dysfunction",
        "increased myocardial atp",
        "intracellular adenosine triphosphate (atp) levels",
        "maintained atp production, and substrate switching favoring fatty acid utilization",
        "succinate and atp production",
        "tca cycle flux and atp levels",
    ],
    "respiratory_function": [
        "decreased respiratory compliance",
        "disordered breathing",
        "eiph",
        "hypoxia-related epochs",
        "impaired lung expansion",
        "impaired oxygenation",
        "lung function",
        "pulmonary flow velocities",
        "pulmonary function",
        "respiration",
        "respiratory function",
        "respiratory rates",
    ],
    "vascular_remodeling": [
        "media thickness",
        "media-to-lumen ratios",
        "pulmonary artery endothelial cell migration/proliferation",
        "pulmonary artery medial thickness",
        "pulmonary artery remodelling",
        "pulmonary artery smooth muscle cell proliferation",
        "pulmonary vascular proliferative remodeling",
        "pulmonary vascular remodeling",
        "tortuosity",
        "vascular adaptations",
        "vascular remodeling",
        "vasomotor changes and hypotrophic remodeling of the aorta",
    ],
    "enzyme_activity": [
        "cardiac dpp4 activity",
        "lactate dehydrogenase activity",
        "lv ace activity",
        "mmp-2 and mmp-9 activity",
        "nfya/sgc activity",
        "pfk-1 (phosphofructokinase 1) activity",
        "protein kinase g (pkg) activity",
        "pyruvate dehydrogenase (pdh) activity",
        "skeletal muscle citrate synthase activity",
        "succinate dehydrogenase and malate dehydrogenase activity, porin expression",
        "superoxide dismutase activity",
    ],
    "muscle_contractility": [
        "ca2+-sensitivity of force production",
        "contractile forces",
        "force generation",
        "isometric specific force",
        "lower absolute maximal force",
        "maximal specific muscle force",
        "muscle force",
        "reduced muscle force",
        "shortening velocity and power",
        "skm contractility",
        "specific force",
    ],
    "vasodilation": [
        "acetylcholine-induced relaxation of aortic segments",
        "conducted vasodilation",
        "direct no donor and endothelial-mediated vasodilation",
        "endothelial-dependent and-independent vasodilation",
        "endothelium-dependent and-independent vasodilation",
        "endothelium-dependent coronary artery relaxation",
        "endothelium-dependent vasorelaxation of resistance vessels",
        "impaired vasorelaxation",
        "impairment in nitric oxide-induced vascular relaxation",
        "isolated coronary arteriole vasodilatory responsiveness in vitro",
        "ns-1619-dependent coronary vasodilatory reserve in vivo",
    ],
    "heart_rate": [
        "chronotropic incompetence",
        "chronotropic response",
        "chronotropic response to reductions in blood pressure",
        "heart rate",
        "heart rate variability",
        "heart rates",
        "hr",
        "resting heart rate",
        "san sensitivity to isoproterenol",
        "tachycardia",
    ],
    "ion_channel": [
        "bkca channel alpha-subunit mrna, protein, or cellular location",
        "calcium ion channels",
        "ica",
        "ina,l",
        "inward rectifier and transient outward k+ currents",
        "l-type ca2+ channel current",
        "l-type ca2+ current",
        "na(+)/ca(2+) exchanger (ncx)",
        "pathological ina,l",
        "transient peak na+ current, l-type ca2+ current, or major k+ currents",
    ],
    "nitric_oxide": [
        "aortic \u2022no production",
        "circulating nitrosothiols",
        "nitric oxide bioavailability",
        "nitrite",
        "nitrite levels",
        "no bioavailability",
        "no production",
        "released nitric oxide levels",
        "total nitroso species",
        "urinary nitrates/nitrites secretion",
    ],
    "pulmonary_congestion": [
        "increased lung weight (pulmonary congestion)",
        "lung congestion",
        "lung edema",
        "lung expression and congestion",
        "pleural effusion",
        "pulmonary congestion",
        "pulmonary edema",
        "pulmonary oedema",
        "wet/dry lung",
        "wet/dry lung ratios",
    ],
    "mitochondrial_ultrastructure": [
        "mitochondrial cristae diffuse dissolution",
        "mitochondrial fission",
        "mitochondrial fission index",
        "mitochondrial morphology and function",
        "mitochondrial structure and function",
        "mitochondrial swelling",
        "morphological abnormalities and mitochondrial damage",
        "reduced mitochondrial density",
        "ultrastructural alterations in the mitochondrial cristae and loss of mitochondrial integrity",
    ],
    "muscle_function": [
        "diaphragm alterations",
        "mitochondrial and contractile functional impairments",
        "skeletal muscle function",
        "skeletal muscle function and mass",
        "skm dysfunction",
        "skm function",
        "skm myopathy",
        "skm myopathy (both atrophy and force loss)",
        "soleus muscle function",
    ],
    "body_weight": [
        "body weight",
        "body weight gain",
        "body weight gain and food intake",
        "increased weight",
        "loss of body weight",
        "weight",
        "weight gain",
        "weight reduction",
    ],
    "hormone_levels": [
        "circulating glp-1",
        "plasma norepinephrine levels",
        "plasma-free testosterone",
        "renin release",
        "serum and myocardial thyroid hormone levels",
        "serum ths",
        "systemic and myocardial norepinephrine",
        "vasopressin levels, gene expression and v2 receptor expression",
    ],
    "lipid_deposition": [
        "accumulation of lipids",
        "hepatic fat content",
        "hepatic steatosis",
        "intramuscular lipid content",
        "lipid droplet accumulation",
        "lipid infiltration in liver",
        "myocardial lipid accumulation",
        "steatosis",
    ],
    "renal_histology": [
        "focal segmental glomerulosclerosis",
        "glomerular damage",
        "glomerular hypertrophy",
        "glomerulosclerosis",
        "renal histology (ie, reduced renal hypertrophy, glomerulosclerosis, and tubular atrophy/dilation)",
        "tubular atrophy",
        "tubular dilation",
        "tubulointerstitial damage",
    ],
    "second_messenger": [
        "camp",
        "camp response within the pln/serca2a microdomain",
        "cgmp",
        "cgmp levels",
        "cyclic guanosine monophosphate (cgmp) expression in cardiac tissue",
        "desensitization of \u03b21-ar stimulated camp pools within the pln/serca2a microdomain",
        "myocardial cgmp level",
        "myocardial levels of cgmp-pkg",
    ],
    "body_composition": [
        "body mass",
        "fat mass",
        "lean mass",
        "lean muscle mass",
        "obesity",
        "skm mass",
        "total body mass",
    ],
    "endothelial_function": [
        "basal nitric oxide",
        "endothelial dysfunction",
        "endothelial function",
        "endothelial function in the carotid artery",
        "microvascular endothelial dysfunction",
        "no-mediated response",
        "von willebrand factor (vwf)",
    ],
    "fibrosis_markers": [
        "collagen i",
        "collagen i and collagen iii",
        "collagen i synthesis",
        "collagen i/iii synthesis",
        "collagen iii",
        "collagen synthesis",
        "collagen synthesis by cardiac fibroblasts",
    ],
    "metabolic_dysfunction": [
        "cardiometabolic dysregulation",
        "metabolic complications",
        "metabolic disorders",
        "metabolic remodeling",
        "metabolic syndrome",
        "metabolic syndromes",
        "severe obesity, increased adiposity, and hyperglycemia",
    ],
    "vascular_histology": [
        "coronary microvascular ec dysfunction",
        "hyperproliferative vascular foci in the subendocardium",
        "lining of the vessel wall by endothelial cells",
        "regression of the peritubular and glomerular microvasculature",
        "small vessel muscularization",
        "vascular rarefaction",
        "vessel fragmentation",
    ],
    "arterial_stiffness": [
        "aortic pwv",
        "aortic stiffening",
        "aortic stiffness",
        "arterial stiffening",
        "coronary elastic modulus",
        "mouse aortic stiffness",
    ],
    "autophagy": [
        "autophagic flux",
        "autophagy",
        "autophagy activity",
        "autophagy dysregulation",
        "autophagy in myocardium",
        "cardiac autophagy",
    ],
    "organ_weight": [
        "heart, liver, spleen, and visceral fat weights",
        "lung weight",
        "lung weight increase",
        "lung/body weight ratios",
        "lung/tl ratio",
        "wet lung weight/tl",
    ],
    "angiogenesis": [
        "angiogenesis",
        "angiogenic defects",
        "apn-mediated angiogenesis",
        "lymphatic endothelial cell (lec) density",
        "reduced branch connections",
    ],
    "muscle_atrophy": [
        "atrophy indexes",
        "fibre atrophy",
        "markers of muscle atrophy",
        "muscle atrophy",
        "skeletal muscle wasting",
    ],
    "physical_activity": [
        "exercise activity",
        "physical activity",
        "reduced activity",
        "running activity",
        "spontaneous physical activity at night",
    ],
    "survival": [
        "decompensation-linked mortality",
        "mortality",
        "survival",
        "survival rate",
        "survival rates",
    ],
    "immunology": [
        "immunoglobulin g deposition",
        "immunologic signatures",
        "splenic t-cell proliferative responses",
        "titres of igg1 and igg2c antibodies",
    ],
    "insulin_resistance": [
        "fasting insulin levels and insulin resistance",
        "homa-ir index of insulin resistance",
        "insulin levels",
        "insulin resistance",
    ],
    "muscle_hypertrophy": [
        "fiber hypertrophy",
        "fiber size",
        "hypertrophy in both oxidative and less oxidative fibers",
        "muscle fiber cross-sectional area",
    ],
    "vascular_reactivity": [
        "ex vivo vasoreactivity",
        "reactivity to phenylephrine",
        "vascular reactivity",
        "vasoconstriction and vasodilatation responses",
    ],
    "antioxidants": [
        "glutathione",
        "levels of antioxidant nrf2",
        "myocardial antioxidant defences",
    ],
    "cardiac_perfusion": [
        "myocardial perfusion",
        "myocardial perfusion reserve (mpr)",
        "peak coronary blood flow velocity",
    ],
    "cell_senescence": [
        "senesce",
        "senescence",
        "senescence markers",
    ],
    "coronary_flow_reserve": [
        "cfr",
        "coronary flow reserve",
        "mpr",
    ],
    "muscle_fatigue": [
        "in vitro muscle weakness and increased fatigability",
        "increased fatigability",
        "muscle fatigue",
    ],
    "muscle_morphology": [
        "fibre-type shift from i to iia",
        "proportion of oxidative fibers in the gastrocnemius",
        "shift towards an oxidative phenotype",
    ],
    "vascular_compliance": [
        "aortic compliance",
        "characteristic aortic impedance",
        "wave reflection",
    ],
    "vascular_permeability": [
        "cardiac leakage of igg and fibrinogen blood-born molecules",
        "endothelial permeability",
        "permeability",
    ],
    "behavioral_parameter": [
        "polydipsia",
        "polyuria",
    ],
    "blood_gas": [
        "ph",
        "plasma ph",
    ],
    "cardiac_imaging": [
        "echocardiography",
        "serial echocardiography",
    ],
    "cell_death": [
        "ferroptosis",
        "pyroptosis",
    ],
    "cell_proliferation": [
        "endothelial cell proliferation",
        "proliferation",
    ],
    "cellular_biology": [
        "peripheral blood hematopoietic stem cells",
        "proportion of the endothelial cell (ec) lineages",
    ],
    "epigenetics": [
        "h3k36me3 enrichment on srebf1 promoter",
        "methylation-sensitive gene expression",
    ],
    "extracellular_matrix": [
        "ecm remodeling",
        "extracellular matrix expansion",
    ],
    "general_outcomes": [
        "benefits",
        "multiple endpoints",
    ],
    "microbiome": [
        "alpha diversity, as indicated by the shannon diversity index",
        "gut microbiome dysbiosis",
    ],
    "physiological_parameter": [
        "core body temperature",
        "muscle po2",
    ],
    "protein_degradation": [
        "ctni proteolysis",
        "reduced proteasome activation",
    ],
    "vascular_resistance": [
        "pulmonary vascular resistance",
        "renal vascular resistance",
    ],
    "biophysics": [
        "intracellular water lifetime",
    ],
    "cell_damage": [
        "lactate dehydrogenase (ldh) release",
    ],
    "cellular_dynamics": [
        "frap dynamics",
    ],
    "cellular_structure": [
        "gap junction density",
    ],
    "general_molecular": [
        "changes partially reversed",
    ],
    "hepatic_function": [
        "hepatic injury",
    ],
    "metabolic_assay": [
        "area under the curve",
    ],
    "molecular_imaging": [
        "[18f]alf-nota-fapi-04 pet/ct imaging",
    ],
    "necrosis": [
        "cardiac necrosis",
    ],
    "nitrotyrosine_levels": [
        "3-nitrotyrosine levels",
    ],
    "omics": [
        "transcriptomic and metabolomic profiling",
    ],
    "organ_function": [
        "liver and kidney function",
    ],
    "peptide_levels": [
        "concentration of et-1",
    ],
    "protein_interaction": [
        "p53/cypd interaction",
    ],
    "protein_synthesis": [
        "protein synthesis",
    ],
    "scoring": [
        "lacrg scores",
    ],
    "stress_response": [
        "endoplasmic reticulum stress",
    ],
}

# Buckets too coarse to compare across papers: they collapse unrelated molecules, so
# "protein expression went up here and down there" is not a disagreement. Outcomes in
# these still count as evidence in the grid and still display -- they are barred only
# from forming contradiction keys.
MEASURE_EXCLUDE_FROM_CONTRADICTION = {"protein_expression", "gene_expression"}

MEASURE_CANON = {raw: canon for canon, raws in MEASURE_GROUPS.items() for raw in raws}
